### ISSUE TITLE
Is there a yearValue ?

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#15]
On books and manuscripts, day and months are always irrelevant. Is it possible to show only year ? Or to turn it into a text field ?

**Comment by mrivoal** [comment]
It is possible for a `knora-base:DateValue` to select only the year. But, as you are using a generic interface, there is no way to show only the year. 
And I don't really like the idea to turn a year into a `knora-base:TextValue`, because you won't be able to use the search functionnalities provided for a date, like searching for dates corresponding to a time interval.
