### ISSUE TITLE
Role/Person problem [Data model change ?]

### ISSUE THREAD

**Issue by cschuwey** [LaDHUL/Theatre-de-societe#7]
Creating a new Agent while creating a new Role doesn't work as it is one step too high in abstraction. 
For instance, if I want to add "Denis Diderot" as a person that was attending the performance (with a name, a birth date, etc…), I can't. Not sure how this must be solved. 

<img width="1139" alt="capture d ecran 2017-03-30 a 15 57 59" src="https://cloud.githubusercontent.com/assets/16320890/24507967/4de94802-1562-11e7-9df9-a56a4ffec7b4.png">

**Comment by mrivoal** [comment]
Isn't it because `Agent` is a class that is not meant to be used directly? 
(That is why I added * next to the label of this resource. See [here](https://github.com/LaDHUL/Theatre-de-societe/commit/6232d404e041dc1ff6da490c77d2d5d675e84e56). BTW, I did a mistake because `Person` can be used directlyn I will fix it).
`Agent` is the superclass of both `Group` and `Person` so you can choose between those two under the `Resource type` field. And if you choose `Person`, then you should be able to add their names, etc.

**Comment by cschuwey** [comment]
So sorry ! I didn't see the menu on the top. Would there be a way of selecting "Person" by default ? It is 95% of the cases when adding an Agent.

**Comment by mrivoal** [comment]
Hum... Nope. I guess the 5% cases in which this property will point to `Group` justify the 

Either we choose the property `roleHasAgent` to point on `Person` (but it won't fit your needs because there is those 5% cases you just mentionned) or we make it point to `Agent` but the downside is that you will have to select the subclass of `Agent` you are pointing to.

**Comment by cschuwey** [comment]
Ok – then we keep like that, that is the most logical way to do it.
